services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"      # 主入口，供 boto3/awscli 使用
      - "4571:4571"      # 可选旧端口（某些工具可能还用到）
    environment:
      - SERVICES=s3                     # 启用 S3（可扩展：dynamodb,sqs,lambda,...）
      - DEFAULT_REGION=us-east-1       # 区域配置（保持和 boto3 一致）
      - DEBUG=1                         # 输出调试日志，方便排查
      - DATA_DIR=/var/lib/localstack   # 数据持久化路径（配合挂载）
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./.localstack:/var/lib/localstack"      # 本地目录挂载，存储 S3 bucket 等状态
      - "/var/run/docker.sock:/var/run/docker.sock"  # 允许容器内调用 Docker（用于模拟 Lambda）

volumes:
  localstack_data:
